import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {Suspense} from "react";
import loremIpsum from "../utils/loremIpsum";


export default function Home() {
  return (
    <>
      <Head>
        <title>React Suspense component issue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
          <div>
            <h1>React Suspense component issue</h1>

            <h2>Issue</h2>

            <p>We use <code>Suspense</code> component in NextJs project to catch server side errors in components and to prevent ruining the whole page as <a href="https://react.dev/reference/react/Suspense#providing-a-fallback-for-server-errors-and-client-only-content">recommended here</a>.</p>

            <p>In React <b>19.1</b> <code>Suspense</code> just renders children on page rendered on server side without JS. So if user without JS opens page, he gets regular page with the content.</p>

            <p>In React <b>19.2</b> <code>Suspense</code> renders fallback and never renders children on page rendered on server side without JS. So now if user without JS opens page, he gets blank page.</p>

            <p>It seems like <code>Suspense</code> does not render children if they are too big while it works fine for smaller children.</p>

            <h2>How to check</h2>

            <ol>
              <li>Switch off JS on this page and reload it.</li>
              <li>Check the first demo and see that <code>Suspense</code> shows fallback instead of children.</li>
              <li>Check the second demo and see that <code>Suspense</code> shows children.</li>
            </ol>

            <section>
              <h2>1. Demo with fallback instead of content</h2>

              <p>This demo contains <b>2</b> paragraphs of text. It makes <code>Suspense</code> component show fallback instead of children during server side rendering 👇</p>

              <h3>Result</h3>

              <Suspense fallback={<>👋 I am a fallback in <code>Suspense</code></>}>
                <p className="restricted-height">{loremIpsum}</p>
                <p className="restricted-height">{loremIpsum}</p>
              </Suspense>

              <h3>Code</h3>

              <pre>
                <code>
                  {`<Suspense fallback={<>👋 I am a fallback in <code>Suspense</code></>}>
  <p>{loremIpsum}</p>
  <p>{loremIpsum}</p>
</Suspense>`}
                </code>
              </pre>
            </section>

            <section>
              <h2>2. Demo with content</h2>

              <p>This demo contains only <b>1</b> paragraph of text so <code>Suspense</code> renders children 👇</p>

              <h3>Result</h3>

              <Suspense fallback={<>👋 I am a fallback in <code>Suspense</code></>}>
                <p className="restricted-height">{loremIpsum}</p>
              </Suspense>

              <h3>Code</h3>

              <pre>
                <code>
                  {`<Suspense fallback={<>👋 I am a fallback in <code>Suspense</code></>}>
  <p>{loremIpsum}</p>
</Suspense>`}
                </code>
              </pre>
            </section>
          </div>
        </main>
      </div>
    </>
  );
}
