const loremIpsum = `Nam eget dapibus magna. Donec dapibus nisl vel sapien cursus dignissim. Donec vitae urna id nisi pharetra ultricies. Morbi bibendum eu nisi nec aliquam. Aliquam condimentum tempus massa non aliquet. Integer ornare sapien eros. Sed non mi enim. Pellentesque id porta quam. Quisque eu tincidunt velit. Mauris pulvinar lobortis massa a lobortis. Nunc vel sem condimentum, feugiat odio hendrerit, lacinia ligula. Curabitur volutpat id est non gravida. Aliquam ipsum nunc, venenatis vel lacus ut, aliquam vulputate augue. Curabitur dapibus, dui at pretium mattis, nibh metus rhoncus nulla, at congue dolor ligula id sapien. Aenean nec nisl ultrices, congue lacus sit amet, condimentum risus. Integer ac libero accumsan, vestibulum risus a, facilisis arcu.

Nulla nec pellentesque diam, non commodo justo. Nulla eget metus lacus. Vivamus mattis imperdiet turpis, nec luctus turpis placerat eget. Curabitur sed sodales diam. Proin eu volutpat lorem. Duis tincidunt dapibus cursus. Proin accumsan diam et erat luctus interdum. Pellentesque in dui sed nulla porta hendrerit. Curabitur at elementum libero. Vestibulum facilisis et felis quis lacinia. Quisque suscipit eget augue at lobortis. Fusce massa justo, rutrum et iaculis at, maximus eu arcu. Ut eu tellus in libero luctus bibendum feugiat quis tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce varius magna quis hendrerit porttitor. Sed a bibendum quam, vel accumsan dolor.

Aliquam erat volutpat. Fusce efficitur eros vitae vehicula mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur fringilla metus et convallis luctus. Integer lorem lectus, rhoncus eget eleifend eu, sagittis sit amet ex. Sed dignissim, purus eget sodales congue, augue tellus vestibulum lectus, et iaculis dolor lacus ac erat. Proin lorem nisi, hendrerit vitae nisl viverra, laoreet tempor odio. Suspendisse condimentum laoreet dignissim. Phasellus sed placerat risus. Donec convallis cursus sapien. Curabitur tempor dolor eget lacus cursus interdum. Sed malesuada tellus eu urna dignissim, nec sodales turpis tristique.

Quisque eget velit odio. Vestibulum eget risus sit amet ipsum varius faucibus a ac ante. Praesent metus neque, ornare nec blandit et, facilisis quis orci. Mauris quam nisi, maximus at egestas id, volutpat quis nisi. Mauris sodales eros mauris, vel feugiat ipsum dapibus id. Maecenas non dictum nisl. Proin porttitor lorem sed risus pharetra, et ultrices lectus convallis. Nullam congue, est sed maximus sagittis, sapien arcu eleifend justo, sed efficitur urna nisl in leo. Nunc sed tempus magna, vitae dignissim sapien. Sed id lectus ligula.

Curabitur sit amet mi pretium, interdum erat eget, molestie dui. Aliquam vitae mauris mattis, tempor augue non, luctus lacus. Aliquam elementum, mi vitae feugiat mollis, urna ex faucibus tellus, sed imperdiet lectus orci ut arcu. Quisque felis augue, elementum non nunc eu, laoreet iaculis lorem. Proin in dictum arcu, at mattis neque. Vestibulum sed tempor nisl, at porttitor massa. Quisque et scelerisque urna. Mauris semper tortor mattis nunc pharetra, nec condimentum dolor accumsan. Sed pharetra odio at semper ultricies. Nulla vel sem ultricies, sagittis sem in, sollicitudin mauris. Aliquam eu ante laoreet, sollicitudin libero quis, porttitor enim.

Nam facilisis auctor fringilla. Sed sed tempus metus. Nam ut nulla urna. Nam eget sapien ut felis sodales malesuada eu non lacus. Duis a lorem lorem. Nulla nec justo erat. Donec pellentesque mauris ac est cursus faucibus. Proin interdum volutpat nisl, nec euismod justo aliquet vel. Proin vel ante erat. In sagittis bibendum tortor, eget malesuada nulla auctor eu. Sed elementum arcu vel venenatis placerat. Sed nec dictum justo. Proin tristique pulvinar lacus, sed porttitor ex ullamcorper nec. Ut rutrum malesuada tortor, id pretium ex convallis in.

Nunc commodo massa a turpis finibus ornare. Suspendisse in mollis ante. Donec tempus sapien a augue auctor, ut volutpat felis euismod. Proin ex elit, volutpat sit amet neque quis, elementum dapibus lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi tempus dictum ante at tincidunt. Aliquam sit amet condimentum lacus. Aliquam erat volutpat. Nulla nec eros nec ipsum bibendum tristique quis in sapien. Aliquam id pulvinar libero.

Curabitur porttitor vel lacus a pellentesque. Ut eleifend, turpis eget venenatis commodo, lacus erat convallis augue, id malesuada ex augue vel libero. Maecenas hendrerit risus quam, at convallis libero interdum convallis. Proin sit amet ornare dui, finibus blandit ex. Nam fermentum justo magna, sed euismod arcu sodales et. Suspendisse feugiat ex ut augue placerat euismod. Aenean eleifend nibh et ante ultrices malesuada. Pellentesque a auctor ipsum. Morbi quis tincidunt mi, in iaculis mauris. Aenean convallis placerat gravida. Sed quis volutpat lacus, et elementum sem. Sed at dapibus ipsum. Proin sed neque mauris.

Pellentesque eget nisi consequat, placerat odio at, dapibus ipsum. Donec maximus, neque at bibendum maximus, risus diam eleifend nisl, id fringilla turpis purus at mauris. Fusce sodales porta urna non bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur mattis purus lacus, ac pharetra eros posuere eu. Sed mi risus, dictum vel purus ac, mattis bibendum ante. Maecenas interdum libero vitae gravida dapibus. Morbi turpis lectus, ultrices placerat mauris sit amet, sagittis bibendum justo.

Curabitur consectetur nisl sit amet suscipit scelerisque. Donec pharetra ac nisi id lacinia. Ut vel tristique nibh. Cras sed mollis velit, quis dictum tellus. Sed iaculis orci libero, vel scelerisque mauris volutpat ut. Etiam sed quam eu lectus lacinia rutrum. Pellentesque quis arcu sapien. Nulla eu sagittis nisl. Nam congue enim sem, non dictum nunc efficitur nec.`;

export default loremIpsum;
